# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/onyx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/etc/data,system/etc/data) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/etc/firmware,system/etc/firmware) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/etc/permissions,system/etc/permissions) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/lib,system/lib) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/vendor/bin,system/vendor/bin) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/vendor/lib/egl,system/vendor/lib/egl) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/vendor/lib/hw,system/vendor/lib/hw) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/vendor/lib,system/vendor/lib) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/vendor/lib/mediadrm,system/vendor/lib/mediadrm) \
    $(call find-copy-subdir-files,*,vendor/oneplus/onyx/proprietary/vendor/lib/soundfx,system/vendor/lib/soundfx)

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api \
    libmdmdetect \
    libqcci_legacy \
    libqmi \
    libqmiservices \
    libqmi_client_qmux \
    libril \
    libmm-abl \
    libtime_genoff \
    libTimeService \
    shutdownlistener \
    TimeService \
    qcrilmsgtunnel \
    ConnectivityExt \
    qcnvitems \
    qcrilhook
